export { default as CalendarIcon } from 'components/icons/Calendar'
export { default as WorkoutIcon } from 'components/icons/Workout'
export { default as WorkoutEditIcon } from 'components/icons/WorkoutEdit'
export { default as ExerciseIcon } from 'components/icons/Exercise'
export { default as ExerciseEditIcon } from 'components/icons/ExerciseEdit'
